### ISSUE TITLE
Illegal string offset

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [ConX/dokuwiki-plugin-authorstats#14]
Hi,
when using the syntax < AUTHORSTATS > without the parameter 'month', I get the following error messages:

Warning: Illegal string offset 'C' in /opt/lampp/htdocs/wiki/lib/plugins/authorstats/syntax.php on line 103
Warning: Illegal string offset 'E' in /opt/lampp/htdocs/wiki/lib/plugins/authorstats/syntax.php on line 103
Warning: Illegal string offset 'e' in /opt/lampp/htdocs/wiki/lib/plugins/authorstats/syntax.php on line 103
Warning: Illegal string offset 'D' in /opt/lampp/htdocs/wiki/lib/plugins/authorstats/syntax.php on line 103
Warning: Illegal string offset 'R' in /opt/lampp/htdocs/wiki/lib/plugins/authorstats/syntax.php on line 103
... {a lot of lines} ...

After that the result is shown as expected.
I've installed the version 2014-08-30.

Best regards
Juergen

**Comment by briangig** [comment]
Actually if you want this sorted in descending order, the correct line is:

        return $this->_getTotalContrib($b) <= $this->_getTotalContrib($a) ? -1 : 1 ;

**Comment by sophron** [comment]
@briangig Do you think you can create a PR for this?

**Comment by ConX** [comment]
This is fixed by #24
