### ISSUE TITLE
limitation on months

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [ConX/dokuwiki-plugin-authorstats#15]
Hi,

using the syntax < AUTHORSTATS 3 > lists not only the users, who edited wiki pages in the last 3 months but also all other users, who contributed wiki pages since the start of the wiki, in this case with a contribution value of '0'

Best regards
Juergen

**Comment by ConX** [comment]
Hello @Juergen-aus-Koeln this got fixed with #24! Thanks for suggesting it.
