### ISSUE TITLE
userhomepage link

### ISSUE THREAD

**Issue by jlAlice** [ConX/dokuwiki-plugin-authorstats#18]
How can it be made the name of an auther to be a link to his userhomepage?

**Comment by zeerd** [comment]
when will we got this changing?

` $output .= "<tr><th>" .`
`userlink($name) . "</th><td>" .`
`$author['C'] . "</td><td>" .`

**Comment by ConX** [comment]
I will do some cleaning soon. If you have any pull requests please submit them.

**Comment by ConX** [comment]
Resolved by #37

**Comment by ConX** [comment]
Resolved by #37
