### ISSUE TITLE
Strange stats

### ISSUE THREAD

**Issue by nheeren** [ConX/dokuwiki-plugin-authorstats#22]
I get some strange stats. Firstly the graph shows a huge peak for November, but we are in October?? And the results for a limited period of time do not correspond the stats without the month argument.
![chart](https://cloud.githubusercontent.com/assets/5136954/4548279/a81d8294-4e53-11e4-94c3-638fd44dbc17.png)
Is this normal?

**Comment by ConX** [comment]
@nheeren Check the new version, it should be fixed.
