### ISSUE TITLE
Usage? Admin panel?

### ISSUE THREAD

**Issue by PPPCR** [ConX/dokuwiki-plugin-authorstats#25]
https://www.dokuwiki.org/plugin:authorstats says:
> After generating the stats from the admin panel
However, I can't find any option in admin panel on Hrun to generate stats.

The fork authorstats**2** I'm running on the server currently does have an admin.php, but this work seems to be deleted from dokuwiki / github.

**Comment by ConX** [comment]
Closing this since it is referring to a previous version of the plugin and installation instructions have been updated.
