### ISSUE TITLE
Implement option for DokuWiki formatted table?

### ISSUE THREAD

**Issue by r0ckarong** [ConX/dokuwiki-plugin-authorstats#27]
I would love to be able to sort the generated table for the various columns. The easiest way to achieve this would be to somehow generate the table in native DokuWiki syntax and wrapping it in the "sortablejs" plugin (https://www.dokuwiki.org/plugin:sortablejs). I've done this for other tables that I've assembled from page includes. Since authorstats generates a non-native format table the other plugin does not recognize the table and you can not sort.

Can you give us a flag e.g. `<AUTHORSTATS NATIVE>` that outputs this as a regular DokuWiki table and not with the class "authorstats-table"?

**Comment by Fabmed** [comment]
Bonjour,

Je suis absent du 16 Mai au 14 Juin 2015.
En cas de besoin, veuillez contacter Médialight par téléphone au 02 62 410 420 ou par email support@medialight.com.

Cordialement,
Fabien BERGER

**Comment by LeDistordu** [comment]
:+1:

**Comment by ConX** [comment]
I tested out the comment that was left plugin's DokuWiki page which suggest wrapping the table with `<sortable>` and it worked:

```
<sortable  1=alpha 2=numeric  3=numeric 4=numeric 5=numeric 6=numeric 7=numeric>
<AUTHORSTATS> 
</sortable>
```
