### ISSUE TITLE
Illegal string offset 'C'

### ISSUE THREAD

**Issue by alexhaller** [ConX/dokuwiki-plugin-authorstats#28]
Hi,

when I use the tag "<AUTHORSTATS>" I get the following error messages:

"Warning: Illegal string offset 'C' in /homepages/7/d212951602/htdocs/webapps/bef/lib/plugins/authorstats/syntax.php on line 103

Warning: Illegal string offset 'E' in /homepages/7/d212951602/htdocs/webapps/bef/lib/plugins/authorstats/syntax.php on line 103

Warning: Illegal string offset 'e' in /homepages/7/d212951602/htdocs/webapps/bef/lib/plugins/authorstats/syntax.php on line 103

Warning: Illegal string offset 'D' in /homepages/7/d212951602/htdocs/webapps/bef/lib/plugins/authorstats/syntax.php on line 103

Warning: Illegal string offset 'R' in /homepages/7/d212951602/htdocs/webapps/bef/lib/plugins/authorstats/syntax.php on line 103"

When I use for example <AUTHORSTATS 60> everything works well.

Thanks a lot for participating in and solving this error!

Best regards
Alex

**Comment by ConX** [comment]
@alexhaller I didn't understand which tag you are using? Could you please provide a minimal working example?

Thank you!
