### ISSUE TITLE
support renamed users

### ISSUE THREAD

**Issue by LMS235** [ConX/dokuwiki-plugin-authorstats#29]
we have changed our user names form "1 letter first name + surname" to "surname + 1 letter first name" now authorstats shows both users.

**Comment by ConX** [comment]
@LMS235 I agree with @splitbrain [1] that this doesn't worth the time as it very uncommon to change all the usernames at once.

If you still want to fix the authorstats you can edit the `authorstats.json` which should update the tables and graphs after your next wiki page change.

[1]: (https://github.com/splitbrain/dokuwiki/issues/1355#issuecomment-139532322)
