### ISSUE TITLE
[feature] List page by authors 

### ISSUE THREAD

**Issue by Zatalyz** [ConX/dokuwiki-plugin-authorstats#32]
Thanks for your plugin, very nice :)

I suggest a feature ; I don't know how make it but maybe someone is interrested to code it ?

Actually, we see number of page created, modified, etc. by one author. This number could become a link pointing to a page displaying the list of pages created by the author. 

Or... other idea : with a syntax like "<AUTHORSTATS AUTHOR=name_of_an_author>", it generate list of page created/modified/etc.

Just an idea to improve it ; it work good without that too !

**Comment by aaronjamison** [comment]
This would be a great feature to add.  Like a listing of the major edits or create contributions.

**Comment by zeerd** [comment]
May http://www.dokuwiki.org/plugin:pagelist give a big helper to implement this.
Or maybe we can find a way to add the creator into tag depends on https://www.dokuwiki.org/plugin:tag.

I will think deeper later and find if anything could do.

**Comment by ConX** [comment]
Resolved by #37
