### ISSUE TITLE
 newest version causing error 405

### ISSUE THREAD

**Issue by 144132** [ConX/dokuwiki-plugin-authorstats#39]
I upgrade dokuwiki-plugin-authorstats to the newest version today.
after I done that

user start to get 405 error when they try to login.

so I try to disable dokuwiki-plugin-authorstats

after I done that

user can login normally

sorry for my terrible english

**Comment by phy25** [comment]
405 is Method Not Allowed which I don't think should happen here. Could you just uninstall and reinstall it?

**Comment by 144132** [comment]
> 405 is Method Not Allowed which I don't think should happen here. Could you just uninstall and reinstall it?

thanks！
first I try to reinstall it without uninstall, but I still got 405 error

so I try to uninstall it  and  reinstall ,  the 405 error is now disappeared.

thanks for your help!

**Comment by ConX** [comment]
I am closing this issue since there aren't many details on how to replicate it.

If this is still an issue, please provide more detail on how to replicate it.
