### ISSUE TITLE
Blank screen after editing a page

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [ConX/dokuwiki-plugin-authorstats#41]
Hi,

for several days now, after editing a page, php aborts with a timeout. When analyzing the problem, it seems that the authorstats plugin is causing the error, because it gives this error message when running the action.php:
```
...
Notice: Undefined index: timestamp in /var/www/html/wiki/lib/plugins/authorstats/action.php on line 115
Notice: Undefined index: timestamp in /var/www/html/wiki/lib/plugins/authorstats/action.php on line 115
Fatal error: Maximum execution time of 30 seconds exceeded in /var/www/html/wiki/inc/JSON.php on line 371
```
When deactivating the plugin everything works fine.

So, what can I do to solve this?

Regards
Juergen

**Comment by bitozoid** [comment]
We had not the same, but a similar error. We fixed by increasing `max_execution_time` in `php.ini`.
