### ISSUE TITLE
Move json files to a cache dir

### ISSUE THREAD

**Issue by bitozoid** [ConX/dokuwiki-plugin-authorstats#42]
Json files are stored in the authorstats plugin directory. This does not look good, as plugin directories are though for code, not for data.

Imho json files are generated from metadata, so they should be moved to some cache directory, e.g. `data/cache/plugin/authorstats`. Then, data would be out of the `lib` directory and diffing code would be easier.

**Comment by luckyleprechauns** [comment]
I made a change to the code that now puts the json files in a sub folder called "data".  It's still inside the plugin's folder, but now it's not next to all of the source code.  The change was just merged in a week ago.

**Comment by bitozoid** [comment]
Thank you for taking the time to deal with this issue. Will you consider putting them into the dokuwiki data directory instead of keeping them in the plugin directory?
