### ISSUE TITLE
Rebuild json files as a job, not as a hook.

### ISSUE THREAD

**Issue by bitozoid** [ConX/dokuwiki-plugin-authorstats#43]
When the config is changed, a full review of the metadata is done to rebuild the json files. If this process takes too long, php may kill its execution.

I wonder whether this process may be done as a job to be run from the admin panel with some progress bar or so, so php may be called by chunks of metadata files.

**Comment by bitozoid** [comment]
I think #41 is related.

**Comment by ConX** [comment]
Hi @bitozoid, I just added an admin page (PR #52) to regenerate the DB through the admin panel. That's still not done in chunks, but the parsing of all files should only be done once after installation. If possible please test it and let me know if it improves this reported issue.
