### ISSUE TITLE
Cannot login after updating plugin

### ISSUE THREAD

**Issue by oldpenguin** [ConX/dokuwiki-plugin-authorstats#44]
Hello
I recently updated authorstats plugin, and I cannot login anymore. I always get Unavailable page or "timed out "message in lower left corner of page. I had to disable plugin (manually renaming the directory) to be able to log in again.
When enabled. I get hundreds of these messages in debug.log:
[...]11:13:10 172.24.91.200: JSON::encode() is deprecated. It was called from authorstatsSaveJSON() in /home/dokuwiki/lib/plugins/authorstats/action.php:153 json_encode should be used instead!
[...]
I am running Release 2020-07-29 "Hogfather" on apache2 on Debian 10/buster

**Comment by oldpenguin** [comment]
Had to downgrade plugin to version ??? (installed manually ConX-dokuwiki-plugin-authorstats-770c1ad.zip)

**Comment by ConX** [comment]
Hi @oldpenguin, are you interested in checking PR #52 to see if that fixes the issue reported here?

**Comment by oldpenguin** [comment]
Hello ConX
I will try it next week and will give some feedback
