### ISSUE TITLE
Name slow to populate or does not populate

### ISSUE THREAD

**Issue by mrtwo88** [ConX/dokuwiki-plugin-authorstats#47]
Release 2018-04-22b "Greebo"  - using default <AUTHORSTATS> takes at least 15 minutes to load Name column.

Less than 20 users with less than 1000 articles.  Statistics load up immediately, but Name column takes a very long time to populate and sometimes does not populate at all.

**Comment by ConX** [comment]
I don't have a 2018-04-22b installation to test this out but it could likely be that this older version is no longer supported by this plugin. Are there any records in your web server's log file that are associated with this bug?

**Comment by mrtwo88** [comment]
I will check to see if I find anything.

Thank you!

**Comment by ConX** [comment]
Closing to focus on issues in more recent DokuWiki versions.
