### ISSUE TITLE
who are these authors?

### ISSUE THREAD

**Issue by asheenlevrai** [ConX/dokuwiki-plugin-authorstats#49]
Hi :)

When I use  < AUTHORSTATS > I get a list of authors and their corresponding number of contribution since the beginning of the wiki.

However, I noticed the following weird things:

 -  I have an author named "(_try_)" with 1130 contributions (that's major compared to most users on my wiki, 5th position). However, there are no such user listed in User Manager. Who is this "try"??'
 - I have a user listed twice in the chart: once as "Benoit VdW" and a 2nd time as "(_benoit_)" there is no other user named "benoit" in User Manager, so I guess these entries correspond to the same user. Why are they split?
 - Some user are displayed as "(_name_)" rather than as "Real Name". This is not necessarily an issue but "_name_" correspond to only their first name. If this can help fix a bug or something...

We use a closed wiki and all new users need to be added to a specific group by the admin (myself) before they can perform any contributions. Users are never deleted. Once they are no longer here, they are just removed from the "contributor" group.

Thanks a lot :)

Best,

-a-

**Comment by ConX** [comment]
Do you have access to the filesystem of the wiki? The plugin works by parsing the files under the /data/meta/ directory to identify the authors and populate their contribution statistics. If you search in these files do you see records of the authors you have listed above?

**Comment by asheenlevrai** [comment]
Thanks for the reply :)

In /data/meta I can find thousands (tens of thousands?) of files that are sorted into directories corresponding to the different namespaces of our wiki (Except one exception where the folders corresponds to a single page, for some reason). In these folders are files that corresponds to each wiki page. Generally there are 3-4 files per page:
 - a .META file
 - a .CHANGES file
 - a .INDEXED file
( - some files without extension)

If I open the .CHANGES files with notepad I can see a list of changes with the corresponding user that made the change. However, it would take forever to go through all the files and search for "_(try)_" or "_(benoit)_" for instance. Also I wonder if the fact that they are displayed in parenthesis in  your plugin is an indication of anything relevant for this purpose.

Let me know if there is another way I should do this :)

Thanks again,
Best,
-a-

**Comment by phy25** [comment]
You can use any modern file editor to do batch search in a folder (e.g. VSCode).

**Comment by ConX** [comment]
Hi @asheenlevrai, I just started a PR and I am wondering if you are still interested in helping solve this issue so that I include the fix in the next update, given that it's been almost a year since you reported it 😄.

**Comment by asheenlevrai** [comment]
sorry @ConX, I missed your previous message.
I'm happy to help in any way possible, obviously.

Best,
-a-
