### ISSUE TITLE
show creates/edits/etc. for past period and not just since beginning of wiki

### ISSUE THREAD

**Issue by jondaniels** [ConX/dokuwiki-plugin-authorstats#50]
Very handy plugin!  I'd love to be able to show contribution types broken out, but for a past period instead of since the beginning of the wiki.  In other words, can the same table columns generated by <AUTHORSTATS> be generated by <AUTHORSTATS #>? (to keep the existing behavior for the latter, a flag could be added).

**Comment by ConX** [comment]
Thanks for submitting this feature request.

Although this feature can be implemented, it would require recreating the user statistics files, which won't be backward compatible. Moreover, based on other submitted issues, initial parsing performance is already a challenge for large DokuWiki installations on low-spec webservers, and I am afraid such a feature would make things worse.
