### ISSUE TITLE
On hogfather, if plugin is enabled, logins and page edits time out- although they do take effect

### ISSUE THREAD

**Issue by craigdrown** [ConX/dokuwiki-plugin-authorstats#51]
PHP logs mentions authorstats errors, and disabling authorstats solves the problem...

**Comment by dryoo** [comment]
When login with this plugin, It triggers 302 redirect, my PHP7.4 uses a cpu with full loads and login takes almost 300 seconds.

**Comment by ConX** [comment]
@dryoo how many pages does your DokuWiki have?

**Comment by dryoo** [comment]
https://openwiki.kr/

11809 pages
16239 medias

now I disabled this plugin.

**Comment by ConX** [comment]
Hi @dryoo, 

That's definitely a large wiki that explains the bad performance.

Do you have the ability to install a plugin from source to test out if there is any improvement in performance? If so, I just pushed a new branch [feat-51-perf-improv](https://github.com/ConX/dokuwiki-plugin-authorstats/tree/feat-51-perf-improv).
